appenders:
  my_stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
  my_file_logger:
    kind: rolling_file
    path: "log/server.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50kb
      roller:
        kind: fixed_window
        base: 1
        count: 50
        pattern: "log/server{}.log"
root:
  level: trace
  appenders:
    - my_stdout
    - my_file_logger